"""
Report Service - generates comprehensive final interview reports.
"""

import uuid
import logging
from typing import Optional

from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError

from app.models.interview import InterviewSession
from app.models.question import Question
from app.models.answer import Answer
from app.models.feedback import Feedback
from app.models.report import Report
from app.models.resume import Resume
from app.ai.nim_service import nim_service

logger = logging.getLogger(__name__)


async def generate_report(db: Session, session_id: str) -> Optional[dict]:
    """Generate or retrieve final interview report."""
    # Check if report already exists
    existing = db.query(Report).filter(Report.session_id == session_id).first()
    if existing:
        return _report_to_dict(existing)

    session = db.query(InterviewSession).filter(InterviewSession.id == session_id).first()
    if not session:
        raise ValueError("Session not found")

    resume = db.query(Resume).filter(Resume.id == session.resume_id).first()
    candidate_summary = resume.candidate_summary or "" if resume else ""

    # Gather all Q&A pairs
    questions = (
        db.query(Question)
        .filter(Question.session_id == session_id)
        .order_by(Question.order_index)
        .all()
    )

    questions_and_answers = []
    total_comm = total_tech = total_rel = total_conf = total_overall = 0
    count = 0

    for q in questions:
        answer = db.query(Answer).filter(Answer.question_id == q.id).first()
        if answer:
            questions_and_answers.append({
                "question": q.text,
                "answer": answer.text,
                "category": q.category,
                "score": answer.overall_score or 5.0,
            })
            total_comm += answer.communication_score or 5.0
            total_tech += answer.technical_score or 5.0
            total_rel += answer.relevance_score or 5.0
            total_conf += answer.confidence_score or 5.0
            total_overall += answer.overall_score or 5.0
            count += 1

    if count == 0:
        count = 1  # Avoid division by zero

    score_averages = {
        "communication": total_comm / count,
        "technical": total_tech / count,
        "relevance": total_rel / count,
        "confidence": total_conf / count,
        "overall": total_overall / count,
    }

    # Generate report via AI (ONE API call)
    report_data = await nim_service.generate_final_report(
        candidate_summary=candidate_summary,
        target_role=session.target_role,
        questions_and_answers=questions_and_answers,
        score_averages=score_averages,
    )

    # Create report with fallbacks
    report = Report(
        id=str(uuid.uuid4()),
        session_id=session_id,
        overall_score=round(score_averages["overall"], 1),
        communication_score=round(score_averages["communication"], 1),
        technical_score=round(score_averages["technical"], 1),
        relevance_score=round(score_averages["relevance"], 1),
        confidence_score=round(score_averages["confidence"], 1),
        interview_summary=report_data.get("interview_summary", "") if report_data else "",
        strengths=report_data.get("strengths", []) if report_data else [],
        weaknesses=report_data.get("weaknesses", []) if report_data else [],
        personalized_roadmap=report_data.get("personalized_roadmap", []) if report_data else [],
        hiring_recommendation=report_data.get("hiring_recommendation", "lean_hire") if report_data else "lean_hire",
        hiring_explanation=report_data.get("hiring_explanation", "") if report_data else "",
        resume_suggestions=report_data.get("resume_suggestions", []) if report_data else [],
    )

    # Update session scores
    session.overall_score = report.overall_score
    session.communication_score = report.communication_score
    session.technical_score = report.technical_score
    session.relevance_score = report.relevance_score
    session.confidence_score = report.confidence_score

    try:
        db.add(report)
        db.commit()
        db.refresh(report)
    except IntegrityError:
        db.rollback()
        logger.warning(f"Report for session {session_id} already generated by another request. Fetching existing.")
        existing = db.query(Report).filter(Report.session_id == session_id).first()
        if existing:
            return _report_to_dict(existing)
        raise

    return _report_to_dict(report)


def _report_to_dict(report: Report) -> dict:
    """Convert report model to dict."""
    return {
        "id": report.id,
        "session_id": report.session_id,
        "overall_score": report.overall_score,
        "communication_score": report.communication_score,
        "technical_score": report.technical_score,
        "relevance_score": report.relevance_score,
        "confidence_score": report.confidence_score,
        "interview_summary": report.interview_summary,
        "strengths": report.strengths or [],
        "weaknesses": report.weaknesses or [],
        "personalized_roadmap": report.personalized_roadmap or [],
        "hiring_recommendation": report.hiring_recommendation,
        "hiring_explanation": report.hiring_explanation,
        "resume_suggestions": report.resume_suggestions or [],
        "created_at": report.created_at,
    }
